"""agregar failed_attempts y locked_until a users

Revision ID: 0e9329aceeac
Revises: 4eef1e4bd791
Create Date: 2026-10-01 20:13:00.798034

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0e9329aceeac'
down_revision: Union[str, Sequence[str], None] = '4eef1e4bd791'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('areas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_index(op.f('ix_areas_id'), 'areas', ['id'], unique=False)
    op.add_column('tickets', sa.Column('area_id', sa.Integer(), nullable=True))
    # Crear el área "General" si no existe y asignarla a los tickets existentes
    op.execute("INSERT INTO areas (name) SELECT 'General' WHERE NOT EXISTS (SELECT 1 FROM areas WHERE name = 'General')")
    op.execute("UPDATE tickets SET area_id = (SELECT id FROM areas WHERE name = 'General' LIMIT 1) WHERE area_id IS NULL")
    op.alter_column('tickets', 'area_id', nullable=False)
    op.create_foreign_key(None, 'tickets', 'areas', ['area_id'], ['id'])
    op.drop_column('tickets', 'area')
    op.add_column('users', sa.Column('is_active', sa.Boolean(), nullable=False, server_default='true'))
    op.add_column('users', sa.Column('failed_attempts', sa.Integer(), nullable=False, server_default='0'))
    op.add_column('users', sa.Column('locked_until', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'locked_until')
    op.drop_column('users', 'failed_attempts')
    op.drop_column('users', 'is_active')
    op.add_column('tickets', sa.Column('area', sa.VARCHAR(), autoincrement=False, nullable=False))
    # WARNING: constraint name is None; this directive will fail as
    # rendered.  Add a name, or use a naming convention; see
    # https://alembic.sqlalchemy.org/en/latest/naming.html
    op.drop_constraint(None, 'tickets', type_='foreignkey')
    op.drop_column('tickets', 'area_id')
    op.drop_index(op.f('ix_areas_id'), table_name='areas')
    op.drop_table('areas')
    # ### end Alembic commands ###
