"""agregar campo area a tickets

Revision ID: 785142507b99
Revises: 53b6062e532e
Create Date: 2026-09-26 22:11:42.009587

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '785142507b99'
down_revision: Union[str, Sequence[str], None] = '53b6062e532e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tickets', sa.Column('area', sa.String(), nullable=False, server_default='General'))
    # Eliminar el default para que inserts futuros exijan el valor explícito
    op.alter_column('tickets', 'area', server_default=None)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tickets', 'area')
    # ### end Alembic commands ###
